### ISSUE TITLE
Use a more recent `kaitai-struct-compiler` release

### ISSUE THREAD

**Issue by woodruffw** [kaitai-io/kaitai_struct_webide#116]
First of all, thanks a ton for both Kaitai Struct and this online IDE! They're both fantastic.

The online IDE appears to be using a fairly old version of Kaitai Struct. From the converted Scala:

```js
$c_Lio_kaitai_struct_BuildInfo$.prototype.init___ = (function() {
  $n_Lio_kaitai_struct_BuildInfo$ = this;
  this.name$1 = "kaitai-struct-compiler";
  this.version$1 = "0.8-SNAPSHOT337369088";
```

Is there any way to get this updated? It'd be nice to be able to use e.g. `meta.bit-endian` in the online IDE.

**Comment by woodruffw** [comment]
I'm not much of a JavaScript person, but I'd expect this line to use the most recent `kaitai-struct-compiler` version:

https://github.com/kaitai-io/kaitai_struct_webide/blob/0d2ad5a67fe2d9802366c9f6c6cd30e1854314ba/package.json#L19

Perhaps there's a deployment side lockfile that needs to be bumped?

**Comment by generalmimon** [comment]
There are two versions of the Web IDE: the stable one deployed at https://ide.kaitai.io/ (which has the stable compiler version by design, which is currently 0.8: ~2 years old at the moment) and the devel Web IDE at **https://ide.kaitai.io/devel/**, which gets updated with every push to the compiler repo (and always has the cutting-edge features, but potentially also some bugs which unintentionally popped with them). See issue https://github.com/kaitai-io/kaitai_struct/issues/573 to see how it works.

So just go to https://ide.kaitai.io/devel/.

**Comment by generalmimon** [comment]
@woodruffw But I fully understand your confusion and the fact that we promote the old sta(b)le Web IDE everywhere, whereas the existence of the fresh [devel Web IDE](https://ide.kaitai.io/devel/) is quite well hidden. It would probably help to at least mention it in the [User Guide](https://doc.kaitai.io/user_guide.html#_web_ide).

**Comment by woodruffw** [comment]
Thanks for the link! I indeed had no idea that the devel Web IDE was available; thanks for the link.
