### ISSUE TITLE
Update ide.kaitai.io?

### ISSUE THREAD

**Issue by abitrolly** [kaitai-io/kaitai_struct_webide#120]
https://ide.kaitai.io reports being at least two years old
```
Kaitai WebIDE version: 0.1-SNAPSHOT-b2479d8 (2018-03-22 10:43:49, license)
Kaitai compiler version: 0.8-SNAPSHOT337369088 (2018-02-05 01:36:23.722)
```
Are there any reasons not to update it with latest changes?

**Comment by GreyCat** [comment]
By convention, https://ide.kaitai.io/ always points to latest stable version. If you want to run IDE with latest development version, use https://ide.kaitai.io/devel/

**Comment by abitrolly** [comment]
@GreyCat nice. I wonder what are the differences between the /devel and the main site over to avoid merging them over this two years?

**Comment by generalmimon** [comment]
> I wonder what are the differences between the /devel and the main site over to avoid merging them over two years?

I don't quite know why you're asking, but here's the diff between stable and devel version of the `kaitai_struct_webide` repo currently: https://github.com/kaitai-io/kaitai_struct_webide/compare/b2479d8..44825a6

I don't think the funcionality of the WebIDE changed somehow significantly (because the Web IDE is not actively developed by anyone for quite a while), it looks like that most visible changes are coming from the recently merged PR https://github.com/kaitai-io/kaitai_struct_webide/pull/95, and then there are a few bug fixes/small enhancements as well.

Naturally, the greatest change will be the KS compiler version bundled inside the Web IDE. The diff of the bundled compiler versions is more interesting: https://github.com/kaitai-io/kaitai_struct_compiler/compare/33655ad..07d71cc

I don't know what you've meant with the _to avoid merging them over two years?_, though.

**Comment by generalmimon** [comment]
@GreyCat:

> By convention, https://ide.kaitai.io/ always points to latest stable version. If you want to run IDE with latest development version, use https://ide.kaitai.io/devel/

Yeah, I've recently also added this info to the [User Guide](http://doc.kaitai.io/user_guide.html#_web_ide).

**Comment by abitrolly** [comment]
> I don't know what you've meant with the to avoid merging them over two years, though.

Usually project stop rolling releases when there is a major change that breaks some essential features. I am curious if there are such broken features in devel?

**Comment by generalmimon** [comment]
I'm closing this because it seems to be resolved.
