### ISSUE TITLE
How to decompress data with snappy

### ISSUE THREAD

**Issue by qiwei9743** [kaitai-io/kaitai_struct_webide#134]
Hi expert,
I'm a newbie.  I just want to decompress data with snappy in webide.
I've read through _User Guide_ and found _Processing: dealing with compressed, obfuscated and encrypted data._ Then I tried below, but not work:
```
- id: body
    size: body_len
    process: xor(0xaa)
    type: snappy
```
Could anyone help to provide some clue?
Thanks.

**Comment by dgelessus** [comment]
Hi! What exactly doesn't work when you try this code? Do you get an error, or does it give you incorrect data?

By default, Kaitai Struct only supports a few common `process` functions (`xor`, `rol`, `ror`, and `zlib`). If you need anything else, you have to implement it yourself as a [custom processing routine](https://doc.kaitai.io/user_guide.html#custom-process). In the web IDE this isn't possible though, because there's no way to load custom JavaScript code into the IDE. So if you need custom processing, you have to install the compiler locally and compile your KSY by hand.

**Comment by qiwei9743** [comment]
Thank you for your reply.  I'll try local compiler.

**Comment by KOLANICH** [comment]
I have implemented a processor (for python) ling ago. https://github.com/kaitaiStructCompile/kaitai_compress/blob/python_fixes/python/kaitai/compress/algorithms/snappy.py
