### ISSUE TITLE
Empty object tree and error on opening ide with zip example

### ISSUE THREAD

**Issue by PSanetra** [kaitai-io/kaitai_struct_webide#159]
I am new to kaitai. I wanted to try the zip example, but it seems like there is an issue with the current build.

When visiting https://ide.kaitai.io/ or starting the current master the following error is shown immediately and the object tree is empty.

```
Parse error (TypeError): DosDatetime is not a constructor
Call stack: TypeError: DosDatetime is not a constructor
    at Zip.LocalFileHeader.LocalFileHeader._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:648:26)
    at Zip.LocalFile.LocalFile._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:164:19)
    at Zip.PkSection.PkSection._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:580:19)
    at Zip._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:145:19)
    at reparse (https://ide.kaitai.io/js/v1/kaitaiWorker.js:96:17)
    at myself.onmessage (https://ide.kaitai.io/js/v1/kaitaiWorker.js:117:47)
```

Is there some quick fix to this?

**Comment by PSanetra** [comment]
ok, it seems like to execute the zip example, you first just need to open `formats/common/dos_datetime.ksy`, which will trigger compiling the file, and then open `formats/archive/zip.ksy`.

**Comment by generalmimon** [comment]
@PSanetra:

> ok, it seems like to execute the zip example, you first just need to open `formats/common/dos_datetime.ksy`, which will trigger compiling the file

Actually, it's usually enough to focus the .ksy pane (by placing a cursor into it) and pressing <kbd>Ctrl</kbd>+<kbd>Enter</kbd> - this forces recompilation of the .ksy spec and reevaluation of the generated parser, which makes the error disappear. Or you can select some other .ksy file in the file tree and then switch back to `zip.ksy`, or double-click an arbitrary binary file in the file tree (even the `samples/sample1.zip` that is preloaded by default). Or you can make some insignificant change to the .ksy contents (for example, adding a newline somewhere) - this also triggers the reevaluation (but for the preloaded specs from the `kaitai.io/formats` library, this will create a fork of the given .ksy spec in the "Local storage" partition with a name ending with `_modified`).

Otherwise, you're completely right - this is an error that "greets" everyone when they first open the Web IDE (which makes for bad user experience and it should have been fixed long ago, but in practice it's not a severe error, just intimidating and annoying). The issue was described in https://github.com/kaitai-io/kaitai_struct_webide/issues/59#issuecomment-692319965. I assure you that this issue is on my radar, I'll probably get around to it within months.

**Comment by simi** [comment]
I just faced this problem and I thought online IDE is broken. It would be great to pick other file/format combination for initial example if current one doesn't work out of box. :thinking:
